/*
 * This file is generated by jOOQ.
 */
package io.github.yuizho.jooq;


import io.github.yuizho.jooq.tables.Division;
import io.github.yuizho.jooq.tables.Product;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.division</code>.
     */
    public static final Division DIVISION = io.github.yuizho.jooq.tables.Division.DIVISION;

    /**
     * The table <code>test.product</code>.
     */
    public static final Product PRODUCT = io.github.yuizho.jooq.tables.Product.PRODUCT;
}
